module.exports = {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
        title: 'Construction Bidding API',
        version: '1.0.0',
        description: 'Test Express API with autogenerated swagger doc',
    },
    apis: [
        "src/**/*.ts"
    ]
}